name: Build on Linux ARM64

on:
  push:
    tags:
      - 'v*.*.*'

jobs:

  build:

    runs-on: ubuntu-latest

    container:
      image: arm64v8/ubuntu:20.04

    steps:

    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        apt-get update
        apt-get install -y cmake gcc g++

    - name: Install rust
      run: |
        curl --proto '=https' --tlsv1.2 https://sh.rustup.rs -sSf | sh -s -- -y
        source $HOME/.cargo/env

    - name: Build release
      run: cargo build --release --target aarch64-unknown-linux-gnu

    - name: Copy artifacts
      run: |
        docker cp ${{ github.workspace }}/target/aarch64-unknown-linux-gnu/release/mybinary .

    - name: Show files
      run: |
        ls ./
